[build]
  publish = "frontend/dist"
  functions = "backend/netlify/functions"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  status = 200
  from = "/*"
  to = "/.netlify/functions/index"
